on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    types: [opened, synchronize, reopened]

name: Main Workflow

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Java env
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Build
      - name: Build project
        run: mvn clean compile
        working-directory: ./code/labflow-backend  # root backend


      # Run SonarQube Scan
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v4.1.0
        with:
          args: >
            -Dsonar.projectKey=Thomas-More-Digital-Innovation_2425-TM_BLC-001-LabFlow
            -Dsonar.organization=thomas-more-digital-innovation
            -Dsonar.sources=code/labflow-backend/src
            -Dsonar.java.binaries=code/labflow-backend/target/classes
