name: Code Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Create database directory
        run: mkdir -p ./code/labflow-backend/databases

      - name: Run Tests with Profile
        run: |
          mvn clean test -Dspring.profiles.active=test
        working-directory: ./code/labflow-backend
